# Generated by Django 4.2.7 on 2023-11-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='main/')),
                ('dataset_image', models.ImageField(upload_to='dataset/')),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
